### PR TITLE
feat: add config support for role

### PR DESCRIPTION
**Pull request by fuergaosi233**
## What kind of change does this PR introduce?

Feat

## What is the current behavior?

Added the option to set Config at creation time, which we can now use to manage the Config of the Role, such as search_path

## What is the new behavior?
We can set role when create.
image

### CODE REVIEW

**Comment by fuergaosi233** [comment]
@soedirgo Pls help me review this pr 🙏

**Comment by fuergaosi233** [comment]
Reping @soedirgo

**Comment by soedirgo** [comment]
Hey there, a couple things:

- Can you check what happens when the of a config is quoted? I see that you do a `literal(v)` there - I don't think that's correct, e.g. for `search_path="extention,public"` in your test (that's a typo btw) it's interpreted as a single element named `"extention,public"`, rathen than two elements `extention` and `public`.
- Can we turn `null`s into `[]` so the type is consistent?
- Can we remove `"op": "test"`? That seems unused, afaict we only need `"add"`, `"replace"`, and `"remove"`.

**Comment by fuergaosi233** [comment]
1. I remove literal
2. Done
3. Why we need change `null` 2 `[]`, i don't get point.
4. Done

**Comment by soedirgo** [comment]
Thanks for the PR!

> Why we need change null 2 []

This would be `{}` now instead of `[]` - the reason is to make the type simpler, since `Record<string, string>` can already represent an empty `config`, so we don't need it to be `Record<string, string> | null`.

**Review by soedirgo — APPROVED** [review]

**Pull request merged**
