### PR TITLE
fix: always sort the table & view columns

### PR DESCRIPTION
**Pull request by kbsali**
## What kind of change does this PR introduce?

As reported in this issue https://github.com/supabase/cli/issues/602
Quite a few users are having issues with generated types randomly changing making it hard to integrate in a CI.

## What is the current behavior?

Only tables and views are sorted, not the columns.

## What is the new behavior?

Hopefully columns would be sorted too although I am not sure how to test this! 😁

### CODE REVIEW

**Comment by soedirgo** [comment]
Thanks! Asking for feedback in the linked issue before merging this.

**Comment by kbsali** [comment]
@soedirgo have you had a chance to get enough feedback? this is really annoying :)

**Comment by sweatybridge** [comment]
I will take a look at this tmr as @soedirgo is on vacation.

**Review by sweatybridge — APPROVED** [review]
LGTM. Alphabetical ordering is desirable based on feedback from CLI issue.

**Pull request merged**
