### PR TITLE
fix: return field name with composite type unknown

### PR DESCRIPTION
**Pull request by kartikk-k**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

[Current behavior - issue #478 ](https://github.com/supabase/postgres-meta/issues/478)

## What is the new behavior?

line 310
```return `${JSON.stringify(name)}: unknown` ```

### CODE REVIEW

**Review by sweatybridge — APPROVED** [review]

**Comment by TomasHubelbauer** [comment]
@sweatybridge This fix doesn't seem to appear in the Supabase CLI version 1.35.0 which was cut yesterday and this PR was merged three days ago. I was under the impression that the Supabase CLI would take the latest version of postgres-meta for its release every time. Is this incorrect? And how can I determine when this fix will be available in the CLI? Thank you 🙏

**Comment by sweatybridge** [comment]
@TomasHubelbauer thanks for following up with these questions. I've bumped pgmeta in CLI 1.35.2 and try to answer some of these below. 

> I was under the impression that the Supabase CLI would take the latest version of postgres-meta for its release every time. Is this incorrect?

Generally for consistency, the CLI uses the same version of pgmeta that's deployed on hosted platform. If there's an urgent or minor fix needed for CLI, we can update early on a per request basis. 

> And how can I determine when this fix will be available in the CLI?

Our release schedule is quite flexible as we are a small team of maintainers. Since the CLI is also an OSS project, we would encourage anyone to contribute a PR for updating the code or dependency versions. By making a PR, you can track the release status of your fix when it is merged.

**Comment by kartikk-k** [comment]
> @TomasHubelbauer thanks for following up with these questions. I've bumped pgmeta in CLI 1.35.2 and try to answer some of these below.
> 
> > I was under the impression that the Supabase CLI would take the latest version of postgres-meta for its release every time. Is this incorrect?
> 
> Generally for consistency, the CLI uses the same version of pgmeta that's deployed on hosted platform. If there's an urgent or minor fix needed for CLI, we can update early on a per request basis.
> 
> > And how can I determine when this fix will be available in the CLI?
> 
> Our release schedule is quite flexible as we are a small team of maintainers. Since the CLI is also an OSS project, we would encourage anyone to contribute a PR for updating the code or dependency versions. By making a PR, you can track the release status of your fix when it is merged.

Can you guide me little bit about updating dependency versions or provide any any reference so that I can make PR and fix this issue?

**Comment by sweatybridge** [comment]
Yup, it's as straightforward as updating the image version used by cli. Here's an example https://github.com/supabase/cli/pull/824/files.

You can find the latest image tag published on [docker hub](https://hub.docker.com/r/supabase/postgres-meta/tags).

**Comment by TomasHubelbauer** [comment]
FYI https://github.com/supabase/cli/pull/838

**Pull request merged**
