### PR TITLE
feat: allow end user to turn on ssl mode for db connections

### PR DESCRIPTION
**Pull request by cpdeethree**
## What kind of change does this PR introduce?

Allows end user to optionally enable SSL mode on db connections 

## What is the current behavior?

Currently the behavior is to disallow all SSL connections and not provide end user the option to allow them

## What is the new behavior?

New behavior is to default to disallow SSL connections but allow end user to allow them via environment variable

## Additional context

While this app is, as the readme states, intended to run in an unexposed environment, there are still valid use cases for having SSL enabled in these kinds of environments.

### CODE REVIEW

**Comment by soedirgo** [comment]
Maybe `PG_CONNECTION` should be named `DEFAULT_PG_CONNECTION` instead to avoid confusion, but you're meant to pass an `x-connection-encrypted` header to specify the DB URL per request. You can enable ssl this way.

**Comment by cpdeethree** [comment]
Makes sense - but the main upstream project that uses this (Supabase) just uses and exposes the default connection string for downstream users: https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L147

And I'm using that via the community helm chart: https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L147

Should I ask there if it makes more sense to pass authentication via the headers? Seems like it might make configuring things a bit more difficult that way in downstream projects that call this and might be a much bigger change

**Comment by soedirgo** [comment]
Ah, I see - seems like it's easier to add this option instead. If you don't mind resolving the prettier check I'll merge this in :+1:

**Comment by cpdeethree** [comment]
fixed by running prettier 👍

**Review by soedirgo — APPROVED** [review]

**Pull request merged**
