### PR TITLE
Optimizing Performance and Resource Utilization with Concurrent Async Execution ✈

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This PR enhances performance and optimizes hardware resource utilization by concurrently executing asynchronous functions using `Promise.all`.

### CODE REVIEW

**Review by kamilogorek — APPROVED** [review]
This will throw on any promise rejecting, but because previous the behaviour was already not handling this correctly, I assume it's fine to change it like that.

**Comment by kamilogorek** [comment]
Need some types updates.

**Comment by sanjaiyan-dev** [comment]
> Need some types updates.

@kamilogorek  Is this correct now ? I hope so.

**Comment by sanjaiyan-dev** [comment]
👀

**Comment by soedirgo** [comment]
Looks good, thanks!

**Pull request merged**
